name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - run: nix develop --command make configure

  lint:
    runs-on: ubuntu-latest
    needs: [configure]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - run: nix develop --command make lint

  analyze:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - run: nix develop --command make analyze

  build:
    runs-on: ubuntu-latest
    needs: [analyze]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - run: |
          nix develop --command build-wrapper-linux-x86-64 \
            --out-dir bw-output \
            make build

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: cachix/install-nix-action@v22

      - name: Run tests
        run: nix develop --command make test

      - name: Generate SonarQube coverage report
        run: |
          nix develop --command gcovr -r . \
            --exclude '.*_autogen/.*' \
            --exclude 'qrc_.*\.cpp' \
            --sonarqube coverage.xml

      - name: Report results to DeepSource
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key cxx --value-file coverage.xml
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

      - name: Run SonarScanner
        run: |
          nix develop --command sonar-scanner \
            -Dsonar.projectKey=hyprview \
            -Dsonar.sources=src,include \
            -Dsonar.tests=test \
            -Dsonar.cfamily.build-wrapper-output=bw-output \
            -Dsonar.coverageReportPaths=coverage.xml \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

