name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - run: nix develop --command make configure

  lint:
    runs-on: ubuntu-latest
    needs: [configure]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - run: nix develop --command make lint

  analyze:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - run: nix develop --command make analyze

  build:
    runs-on: ubuntu-latest
    needs: [analyze]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - run: nix develop --command make build

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }} # important for DeepSource
      
      - uses: cachix/install-nix-action@v22

      - run: nix develop --command make test

      - name: Generate coverage report
        run: |
          nix develop --command gcovr -r . --json -o coverage.json

      - name: Report results to DeepSource
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key cxx --value-file coverage.json
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}


